/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package interfaz;

import datos.usuario;
import interfaz.internalFrames.fPermisos;
import javax.swing.JFrame;

/**
 *
 * @author derek
 */
public class fMain extends javax.swing.JFrame {
    usuario usu;
    boolean subUser = false;
    /** Creates new form fMain */
    public fMain(usuario usu) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.usu = usu;
        cargarDataUsuario();
        mnuTrabajador.setVisible(usu.isTrabajador());
    }
    
    public fMain(usuario usu, boolean internal){
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.usu = usu;
        cargarDataUsuario();
        if (internal) {
            this.setTitle(this.getTitle() + " [" + usu.getUsuario() + "]");
            this.setExtendedState(JFrame.NORMAL);
            this.setAlwaysOnTop(true);
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            mnuPermisos.setVisible(false);
            mnuSalir.setVisible(false);
            subUser = true;
        }
        
    }
    
    void cargarDataUsuario(){
        mnuUsuario.setText(usu.getNombre());
        mnuNombreUsuario.setText("Nombre: " + usu.getUsuario());
        mnuCorreo.setText("Correo: " + usu.getCorreo());
        mnuDireccion.setText("Direccion: " + usu.getDireccion().replace("\n", "  "));
    }

    void abrir(javax.swing.JInternalFrame frm){
        desktop.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuario = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mnuEditar = new javax.swing.JMenuItem();
        mnuNombreUsuario = new javax.swing.JMenuItem();
        mnuCorreo = new javax.swing.JMenuItem();
        mnuDireccion = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuTrabajador = new javax.swing.JMenu();
        mnuPermisos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Bicicletas");
        setLocationByPlatform(true);

        mnuUsuario.setText("Usuario");

        jMenu1.setText("Info");

        mnuEditar.setText("Editar");
        mnuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEditar);

        mnuNombreUsuario.setText("Usuario");
        mnuNombreUsuario.setEnabled(false);
        jMenu1.add(mnuNombreUsuario);

        mnuCorreo.setText("Correo");
        mnuCorreo.setEnabled(false);
        jMenu1.add(mnuCorreo);

        mnuDireccion.setText("Dirección");
        mnuDireccion.setEnabled(false);
        jMenu1.add(mnuDireccion);

        mnuUsuario.add(jMenu1);

        mnuCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCerrarSesion.setText("Cerrar Sesion");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuCerrarSesion);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuSalir);

        jMenuBar1.add(mnuUsuario);

        mnuTrabajador.setText("Trabajador");

        mnuPermisos.setText("Permisos de usuarios");
        mnuPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPermisosActionPerformed(evt);
            }
        });
        mnuTrabajador.add(mnuPermisos);

        jMenuBar1.add(mnuTrabajador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
        this.dispose();
        if (!subUser) {
            new fLogin(null).setVisible(true);
        }
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarActionPerformed
        fEditarUsuario frmEditar = new fEditarUsuario(this, true, usu);
        frmEditar.setVisible(true);
        usu = frmEditar.usu;
        cargarDataUsuario();
    }//GEN-LAST:event_mnuEditarActionPerformed

    private void mnuPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPermisosActionPerformed
        abrir(new fPermisos());
    }//GEN-LAST:event_mnuPermisosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuCorreo;
    private javax.swing.JMenuItem mnuDireccion;
    private javax.swing.JMenuItem mnuEditar;
    private javax.swing.JMenuItem mnuNombreUsuario;
    private javax.swing.JMenuItem mnuPermisos;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu mnuTrabajador;
    private javax.swing.JMenu mnuUsuario;
    // End of variables declaration//GEN-END:variables

}
